name: Build

on:
  workflow_dispatch:
    inputs:
      tasks:
        description: 'tasks.json'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - run: npm i -g @antfu/ni pnpm rimraf cross-env
      - run: echo '${{github.event.inputs.tasks}}' > oncall.json

      - name: Build
        run: npx knightly -c oncall.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
