name: Scheduler

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - run: npm i --only=prod

      - name: Distribute
        run: npm run distribute
        env:
          GITHUB_TOKEN: ${{ secrets.ANTFU_GITHUB_TOKEN }}
