name: Update Tasks

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - run: npm i --only=prod

      - name: Update Tasks
        run: npm run update-tasks

      - name: Add
        uses: EndBug/add-and-commit@v4
        with:
          message: 'chore: update tasks'
          add: 'README.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
